on: push
name: "Build, Test & Deploy 🚀"
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'no-ci')"
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.17
        uses: actions/setup-node@v1
        with:
          node-version: 10.17
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-push_deploy-${{ hashFiles('package.json') }}
      - name: Install Dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Check Build
        run: npm run-script build
      - name: Check Tests
        run: npm run-script test
      - name: Deploy to npm! 🚀 (if master branch)
        if: github.ref == 'refs/heads/master'
        uses: benwinding/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
